# Generated by Django 3.2.7 on 2025-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a6efa1', max_length=6),
        ),
    ]
