# Generated by Django 3.2.7 on 2025-11-07 10:37

from django.db import migrations, models
import twofa.models


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default=twofa.models.generate_otp, max_length=6),
        ),
    ]
