# Generated by Django 3.2.7 on 2025-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='d4a01c', max_length=6),
        ),
    ]
