# Generated by Django 3.2.7 on 2025-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefactor', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='bb4b0c', max_length=6),
        ),
    ]
